---
title: | 
       Technical Documentation \
       BC Demographic Survey: DIP Data Linkage Rates
output:
  word_document:
    reference_docx: template-docx.docx
    toc: yes
    toc_depth: 3
bibliography: refs.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**PROJECT:** Evaluating the BC Demographic Survey Data in the DIP
  
**PREPARED BY:**  
Amelia Lowery, Julie Hawkins & Lindsay Fredrick  
Data Science Partnerships Program  
BC Stats
BC Data Systems    
Ministry of Citizens' Services  
  
**DATE:** `r Sys.Date()`  

\newpage

# Purpose

This document summarizes the analytical methods, caveats, and technical software used to generate the linkage summaries provided in the dashboard [BC Demographic Survey: DIP Data Linkage Rates](https://bcstats.shinyapps.io/bcds-dip-compare/) and made available on the [BC Data Catalog](https://catalogue.data.gov.bc.ca/)


# Project Overview

In 2023, BC Stats conducted the <a href="https://antiracism.gov.bc.ca/"> BC Demographic Survey</a>. More than 200,000 people responded to the voluntary survey, providing information about many aspects of their identity  (such as race, ethnicity, ancestry, gender and many others). 

The <a href="https://www2.gov.bc.ca/gov/content/data/about-data-management/data-innovation-program/"> Data Innovation Program (DIP)</a> securely links and de-identifies data from multiple ministries, organizations or agencies in a secure platform. Many DIP datasets also contain demographic related information. However, the number of datasets with demographic information is limited, and are only partially complete pictures. The BC Demographic Survey aims to improve our understanding of how people with varying backgrounds interact with public services by broadening the scope of available demographic information to each data (and therefore service) provider.

The analysis presented in this dashboard used the secure platform to access available datasets from the DIP, and linked these datasets, where possible, to the data from the BC Demographic Survey. Overall linkage rates were investigated. The methods, tools, and caveats associated with the dashboard are explored more fully below. 


# Methodology

## Overview

To compare the BC Demographic Survey to each individual DIP dataset, a list of unique StudyIDs (which represent unique individuals as determined by PopData) was created for each individual dataset. The BC Demographic Survey list was compared to the individual DIP dataset, to determine:

* The number of individuals in each DIP dataset.
* The number of individuals within a DIP dataset that have a survey record.


## Caveats

**This dashboard and data source serves as a guide only. Researchers are ultimately responsible for determining the feasibility and reliability of the variables themselves prior to using the BC Demographic Survey variable information for their project.**

Here we list some important distinctions to keep in mind when browsing the dashboard and related datasets:

* This dashboard was produced in 2024. Linkage rates will change overtime.
* Not every DIP dataset has a StudyID.
* Some DIP datasets contain multiple StudyIDs.
* All counts provided here are unweighted. DIP researchers are responsible for providing their own weights where necessary.
* To mitigate the privacy risks of re-identification and residual disclosure, some small counts (and associated percentages) have been masked. 
* Rounding has been performed on all percentages.

## Software

This analysis is implemented in the R and python programming languages [@Rcore, @van1995python]. The code used to generate this analysis was reviewed by three data scientists. Key tools used to complete this work include the Apache Arrow project [@arrow], the tidyverse [@wickham] and the internal SAE package dippy [@dippy]. 

### GitLab

All code is stored under the [git version control](https://git-scm.com/) system and shared inside the secure environment in these GitLab repos:

- Creation of Demographic Survey Variables: <https://projectsc.popdata.bc.ca/shares/arda-demographic-survey>
- Creation of Linkage Statistics: <https://projectsc.popdata.bc.ca/shares/linkage-litmus-test>

# References

